### PR TITLE
Add: Grove - SGP41 with ATH20 (on Seeeduino Nano)

### PR DESCRIPTION
**Pull request by hbswn**
Probably not complete or ready, but good enough to get some feedback.

### CODE REVIEW

**Comment by hbswn** [comment]
Have I pushed the wrong button?   ("update from main branch" after your commit)

**Comment by MatthewJeffson** [comment]
Nope, everything is fine here:D
I'm currently is dealing with other things. This might take a while;)

**Comment by hbswn** [comment]
I closed this pull request, because I had one commit with an old (non-existent) e-mail address.

**Comment by hbswn** [comment]
Replaced with pull request [671](https://github.com/Seeed-Studio/wiki-documents/pull/671).

**Pull request closed without merging**
