### PR TITLE
Organises tinyML workshop page  

### LINKED ISSUE #488: [Page Add] TinyML workshop
# This assignment has been successfully achieved 🎉

Thanks Salman and the wiki page is: https://wiki.seeedstudio.com/tinyml_workshop_course_new/

## Overview
- We need your help to update the Wiki content about [TinyML workshop](https://wiki.seeedstudio.com/tinyml_workshop_course/).
- Make the workshop tinyML more easy and accessible
- The purpose is really How users can easily run the whole course using the wiki.
## What we are trying to present:
1. ([EdgeLab part](https://wiki.seeedstudio.com/tinyml_workshop_course/#1-edgelab))Using EdgeLab webpage to quickly run two models: Face Detection and Digital Meter Detection. -- This will make the participants instantly getting to know the features of XIAO ESP32S3 Sense (camera and TinyML capability)
2. ([Edge Impulse part from 2.1 to 2.2](https://wiki.seeedstudio.com/tinyml_workshop_course/#2-edge-impulse)) Using Arduino pre-trained libraries which are Speech Keyword Recognition and Fruit Identification to quickly get to know how to use Arduino IDE to achieve ML implementation.
3. ([Edge Impulse part 2.3](https://wiki.seeedstudio.com/tinyml_workshop_course/#23-edge-impulse-kws-application-in-xiao-esp32s3-sense)) Taking KWS application as an example to show the participants how to run the entire process of deploying the ML model using Edge Impulse.
4. The rest will be left to the participants who are familiar with Arduino and ML better and do their own DIY models.
## How do we work together?
- **Leave a comment with your GitHub name below** as you accept this assignment and will complete the contents about what we are trying to present.
- The maintainer will assign and record you as our only contact for this assignment.
- You can first [Deploy this Wiki Platform Locally](https://wiki.seeedstudio.com/Deploy_Page_Locally/) (The entire source code .zip file is only 30 M)
- You will be invited as our **"Contributor"** once you ["Pull Request"](https://wiki.seeedstudio.com/Contribution-Guide/).
- The maintainer will review the PR and then merge.
## What do we offer?
We want to express our gratitude to our contributors by offering a range of rewards.  Depending on the difficulties(Tier 0/1/2/3), the time we expect(Days 1/3/7/15),  the actual  submission time and the actual submission contents, we will offer different levels of rewards.
1. We will provide our products or cash bonus to our contributors as a token of appreciation.
2. For those contributors who join our "Ranger Program"(announced soon), we offer even more exciting rewards, including access to our prototype products.
3. In addition, all contributors and their contributions will be acknowledged and showcased on our wiki platform.
## FAQ
- For any question, the contributor can directly commend here.

### PR DESCRIPTION
**Pull request by salmanfarisvp**
- Added a new section for easy followup 
- Added Diagram images for easy understanding 

ToDo
- Image classification project library 
- Image classification project full instructions.

### CODE REVIEW

**Review by MatthewJeffson — APPROVED** [review]
Thank you so much for the update!

**Comment by MatthewJeffson** [comment]
Hi @salmanfarisvp! @limengdu has updated some contents - it has integrated ESP tool function into EdgeLab #509 . Would you mind updating here as well?

**Comment by salmanfarisvp** [comment]
@MatthewJeffson That's cool. And Sure, I'm on it. 

as we discussed, the resource is fetched from [my own repo](https://github.com/salmanfarisvp/TinyML/tree/main) for now .

**Comment by MatthewJeffson** [comment]
@salmanfarisvp Yes! I can see it.

**Comment by salmanfarisvp** [comment]
@MatthewJeffson Updated the doc as Edge Lab as flashing tool. see https://github.com/Seeed-Studio/wiki-documents/pull/507/commits/cc296d1ec203c99de0f82ae3295f1959bf8b1f1a

**Comment by MatthewJeffson** [comment]
Hi, @salmanfarisvp I can see it 👌

**Comment by salmanfarisvp** [comment]
@MatthewJeffson Could you please check the [conflict](https://github.com/Seeed-Studio/wiki-documents/pull/507/conflicts) and see if we can use the latest version? Many thanks.

**Comment by MatthewJeffson** [comment]
Hi, @salmanfarisvp Eric has checked the wiki we have now and he will go through the workshop with it tomorrow.
The structure and contents are looking good! 
We can go ahead and finish and then publish them.:D

**Comment by MatthewJeffson** [comment]
By the way, may I ask when do you think these two will be published?
image

**Comment by salmanfarisvp** [comment]
@MatthewJeffson Fruit Identification is added and working on the "Building Image classification project". It will be out soon.

**Comment by salmanfarisvp** [comment]
@MatthewJeffson Could you please check the [conflict](https://github.com/Seeed-Studio/wiki-documents/pull/507/conflicts) and see if anything I need to do. Thanks.

**Comment by MatthewJeffson** [comment]
@salmanfarisvp Oh, I forgot it sorry XD

**Comment by salmanfarisvp** [comment]
@MatthewJeffson  I see it's not deployed the changes yet, Do you know what's the issue?

I see` Deploy to GitHub Pages / deploy (pull_request) Skipped` what will be the issue?

**Comment by MatthewJeffson** [comment]
Oh, that is the GitHub action for deploying the page when some changes or adds have been committed or merged to this repo. You can check them in the "GitHub" section.
As I mentioned before, we can keep updating and then publish them once the materials are ready. 
Eric will host the workshop using [the wiki we have now](https://wiki.seeedstudio.com/tinyml_workshop_course/)
Once he finished and the contents here were really, I will merge it and the "deploy" GitHub action will automatically deploy our materials as new web pages.

**Comment by MatthewJeffson** [comment]
The previous two show fine and the contents here are fine. no worry about it.

**Comment by salmanfarisvp** [comment]
Thanks and I will push the final document in a few minutes and let you know to run the deployment. FYI, I'm also taking a hands-on session tomorrow in my local area. Excited 🥳

**Comment by MatthewJeffson** [comment]
> Thanks and I will push the final document in a few minutes and let you know to run the deployment. FYI, I'm also taking a hands-on session tomorrow in my local area. Excited 🥳

Wow! Thank you for such fast posting! Congratulations and good luck with your hands-on session tomorrow!

**Comment by salmanfarisvp** [comment]
@MatthewJeffson All done for now, I checked the code and documentation myself, please review and merge it. I can't wait to see the demo on the main page. Thanks for the support.

**Review by MatthewJeffson — APPROVED** [review]
Thanks for the add up!

**Pull request merged**
