### PR TITLE
Add: round display christmas wiki

### PR DESCRIPTION
**Pull request by limengdu**

### CODE REVIEW

**Comment by limengdu** [comment]
@feiticeir0

**Comment by limengdu** [comment]
The link to your document is: https://wiki.seeedstudio.com/round_display_christmas_ball

**Comment by meilily** [comment]
@feiticeir0 Hi Bruno, will you also consider publishing this cool project tutorial on [Hackster](https://www.hackster.io/), or [Instructables](https://www.instructables.com/)? In this way, more people from the community can also enjoy this joyful holiday creation!

**Comment by feiticeir0** [comment]
> @feiticeir0 Hi Bruno, will you also consider publishing this cool project tutorial on [Hackster](https://www.hackster.io/), or [Instructables](https://www.instructables.com/)? In this way, more people from the community can also enjoy this joyful holiday creation!

Hi @meilily  ! Sure, just give me a couple of days to do it !  Thank you !

**Comment by meilily** [comment]
Awesome. Looking forward to it!

**Comment by feiticeir0** [comment]
@meilily  Here's the link to the project on Hackster.io 

[Round Display for XIAO Christmas Ball](https://www.hackster.io/feiticeir0/seeed-studio-round-display-interactive-christmas-snow-globe-65b972)

Later for instructables

**Comment by feiticeir0** [comment]
Here's the instructables project:
[Round Display for XIAO Christmas ball](https://www.instructables.com/Seeed-Studio-Round-Display-for-XIAO-Christmas-Ball/)

**Pull request merged**
