### PR TITLE
Add: Grove - SGP41 with AHT20 ( on Seeeduino Nano )

### PR DESCRIPTION
**Pull request by hbswn**
Same as my Friday pull request, but only one commit with the correct author e-mail.
Corrected: the temperature and humidity sensor is AHT20, **_not_** ATH20.

### CODE REVIEW

**Comment by hbswn** [comment]
Is this one so difficult?

**Comment by MatthewJeffson** [comment]
Hi @hbswn Hans!
Sorry about holding this so long. The contents will be changed a little but we are kind of short of hands right now. This is the very reason that we came up with the Contributor Program as you can see on the "Project" portion. - We are looking for people who can help us with more projects.
Your contribution here is really good and I think I will review and change something here, in two or three days:D
Best Regards,
Matthew

**Comment by hbswn** [comment]
Ah, okay.

I noticed the checks passing for the other pull requests, but I see some results for mine, now too.
I was just wondering, whether I had missed something or so.

thanks for the answer,

Hans

**Review by MatthewJeffson — APPROVED** [review]
Hi, the contents are changed already.
Thank you for doing it!

**Comment by hbswn** [comment]
Note sure whether comments on closed pull requests will be noticed.

My **ATH** typo made it into the URL of the final page: https://wiki.seeedstudio.com/grove-sgp41-with-ath20/

See commit [bfe08843ea346de5f00b60d467dced4b005785b4](https://github.com/Seeed-Studio/wiki-documents/pull/671/commits/bfe08843ea346de5f00b60d467dced4b005785b4) .
Can this still be corrected?

It make sense to publish this as an application and keep the sensor documentation to the bare minimum.
But then I'd also improve the C code. I kept it close to the code published for the sensors.

Hans

**Comment by MatthewJeffson** [comment]
Hi! Yes it can be corrected. Sorry about that.
And this is kind of like a project and you are using Seeeduino Nano I think it can be stored in the application part of the seeeduino series boards.
Matthew

**Pull request merged**
