### PR TITLE
Update ESP32-Arduino examples to v3 i2s

### PR DESCRIPTION
**Pull request by lucyknada**
Tested locally, based on migration guide and new docs over at: https://docs.espressif.com/projects/arduino-esp32/en/latest/api/i2s.html

This does not update the save to microSD part yet (record_wav), as that needs separate testing.

### CODE REVIEW

**Comment by lucyknada** [comment]
tested and porting the wav recording example works similarly too, if this gets merged I can add a PR for that too.

**Comment by limengdu** [comment]
Thank you for submitting your update, our engineers are in the process of verifying it, please wait. @Allen-Kuang

**Comment by Allenkzl** [comment]
Hello  @lucyknada ,  thank you for your commit~ 
I would like to ask you a question. There was a error when I compile your code, which is about the "setPinsPdmRx" method. I attach an image so that you can check if you met this problem before. Another image is about the usage in offical document and it seems different to your usage.
I2S_official
I2S_fix

**Comment by lucyknada** [comment]
@Allen-Kuang are you using v3 of esp32-arduino? these functions are only in 3.0.x onward, v2 still relies on setAllPins()

**Comment by Allenkzl** [comment]
Yess~  My ESP32 version is  3.0.1 @lucyknada 
I2S_fix2

**Comment by lucyknada** [comment]
@Allen-Kuang I tried it with a fresh installation and never used esp32s3-sense; it still works.

image

something in your setup is making it try to resolve for alternatives; none of my setups do, so I'd investigate that; maybe just reinstall the esp32 library or uninstall the other esp32 provider by arduino:

image

and try again; I assume it's providing headers too possibly.

**Comment by Allenkzl** [comment]
In fact, almost all of those using I2S are XIAO ESP32-S3 Sense, so we must arrange time to solve this problem. Thank you for your comtribution again~ I will try the method you mentioned above. If it has any progress I will let you know ~ @lucyknada

**Comment by limengdu** [comment]
image
There's nothing wrong on my end.

**Review by limengdu — APPROVED** [review]

**Comment by Allenkzl** [comment]
I use a new enviroment to test it, it works~
Indeed, it's my old enviroment issuse.

**Pull request merged**
