### PR TITLE
SenseCAP Indicator Matter Demo page

### LINKED ISSUE #516: [Page Add][Enhanced Function] SenseCAP Indicator applies the Matter 1.0 protocol
# This assignment has been successfully achieved 🎉

Thanks Tim and the wiki page is: https://wiki.seeedstudio.com/SenseCAP_Indicator_Application_Matter/

## Overview
- Use [SenseCAP Indicator](https://www.seeedstudio.com/SenseCAP-Indicator-D1-p-5643.html) to apply the Matter 1.0 protocol and connect with iPhone or Google services(HomeKit).
- Use iPhone and control the local sensors with Matter.
- Indicator's onboard sensors, Grove sensors, and proprietary protocol LoRa node devices are converted to Matter-enabled devices
## Assignment acceptance
- Please check the "assignee" section before accepting to see if this has already been accepted.
- Please ensure that the **requested timeline** aligns with your workflow.
- Leave your **Github Name** below to indicate that you are willing to accept the job.
- If you are taking on the assignment **for the first time**, you may receive an invitation in your GitHub mail.
## Requirements(check list)
- Prove of video presentation
- Detailed operation procedure written in **Markdown file** with [wiki standards](https://files.seeedstudio.com/wiki/wiki-ranger/Standards_of_Product_ApplicationWiki_Upload.pdf)
- Upload wiki markdown file to GitHub repository with [guide & instructions](https://wiki.seeedstudio.com/Contribution-Guide/)
- List of products used
- Code files that complete the program
## What do we offer?
We want to express our gratitude to our contributors by offering a range of rewards.  Depending on the difficulties(Tier 0/1/2/3), the time we expect(Days 1/3/7/15),  the actual  submission time and the actual submission contents, we will offer different levels of rewards.
1. We will provide our products or cash bonus to our contributors as a token of appreciation.
2. For those contributors who join our "Ranger Program"(announced soon), we offer even more exciting rewards, including access to our prototype products.
3. In addition, all contributors and their contributions will be acknowledged and showcased on our wiki platform.
## FAQ
For the ranger who accepts this assignment can have a conversation with your transition AE below

### PR DESCRIPTION
**Pull request by Timo614**
Adding this document re: the SenseCAP Indicator project. Let me know if you want me to expand in any area here in more detail. Given a lot of the configuration here is automatic I went into some detail about the changes needed to modify the the logic to support changing the dashboard that was added for this demo project.

Let me know if you we were thinking something else here and can adjust further.

Is there some step to add a page to the left hand sidebar? I wasn't seeing it render for my page here oddly. I had to type it in specifically to the address to visit the page as well (in case I'm missing some configuration step to have it included in the nav?).

Will link this back to the associated project request.
Screenshot 2023-08-29 at 1 08 55 AM
Screenshot 2023-08-29 at 1 09 24 AM
Screenshot 2023-08-29 at 1 19 57 AM

### CODE REVIEW

**Comment by MatthewJeffson** [comment]
Hi @Timo614 Sorry I might miss some information on the standards and here is the [template wiki](https://wiki.seeedstudio.com/Name_your_website/) that maybe helpful.

And I think it will be better to have some images or gifs or video(like you have [previously](https://photos.google.com/share/AF1QipNSgP0x3VHC4D1SGsiRcTuWa9qzAcE7PdVfn3XSmnu2Wm38uMu8VvHdaM1O17W-fw?key=d1VPV3JkRlVyd3M4MzFmd1dpb1dvdEsxOGN1c3RR)) attached:

1. what is it look like when finished one step
2. or the example look like for the configuration. 

If you have some, you can send images to me and I will assist to add in the file.

**Comment by MatthewJeffson** [comment]
And regarding the left side bar, you can find a ".js" file in the "wiki-document" folder

image

Put the file as relative path and store with the same format and then the ".md" file will be displayed on the left bar.
Regards

**Comment by Timo614** [comment]
matter-1
matter-2

I've attached two demo photos here but I'm not sure on the process to upload to the files subdomain used by the wiki. From what I could gather the images themselves are not in the wiki repo but hosted somewhere else but I not entirely sure. Apologies.

Let me know if you want me to expand on any areas. I can explain in the wiki how the device maps back to the Matter device (showing the setup of the nodes and then the update call as code snippets) but wasn't sure how much detail was needed there.

For the video at the top -- I wasn't sure if that was something that Seeed wanted to do itself vs my video for the demo. I can do something more professional for that if needed I just thought it was for showing off the pull request. I can edit my video to make it more coherent and upload it to youtube for linking if need be just wanted to confirm before spending too much time there.

**Comment by MatthewJeffson** [comment]
Hi @Timo614 Tim, my apologies for the confusion here. Take one of our contributor work([MicroPython for ESP32C3](https://wiki.seeedstudio.com/XIAO_ESP32C3_MicroPython/)) as an example, we just want the wiki to be as easy to understand as possible, for everyone(even beginner) can knowledge and be able to accomplish the project.

1. First, there will be a video to show what the project looks like and an overview introduction.
2. Then introduce the hardware or software needed.
3. The next part is the main part where it should be step by step showing how to use the hardware and software above to achieve the outcome, i.e. to achieve what you have in your video. 
     (Attach visuals/images for each step will be even more perfect. The images for wiki are all stored in a server we holding so if you have any,  you can just email them to me)
5. The final part is "What's more" and just mentions something you want viewers to know, the code definition, the further supported libraries, etc...

This is an easy, however time-consuming part - the documentation writing.
Hope this will make it clearer.

It is fine you may not have time for this, I will cover the rest content and publish the wiki in your name.

And... would you mind editing the video and giving me your address on YouTube? I will be really grateful.

Best Regards,
Matthew

**Comment by Timo614** [comment]
Sure, this all sounds good, I can make the adjustments here.
Sorry for the back and forth. I'll use that associated guide as a reference and improve upon this and include additional files here with the configuration and usage flows when complete.

**Comment by Timo614** [comment]
I'll also make a new video specifically for the wiki page itself. Apologies there, I had thought the video was to demonstrate the project for the purposes of the task not for the wiki page (I had thought someone from Seeed was going to do a video like the Home Assistant one but I don't mind doing it).

**Comment by MatthewJeffson** [comment]
Nice! Thank you so much for doing that!
Best Regards,
Matthew

**Comment by Timo614** [comment]
I've pushed up some additional changes. I still need to add the demo video showing the SenseCAP Indicator actually in use (for the top video) -- going to handle that tonight once my kids go down. I also need to add some photos in the application section but is this more along the lines of what you were thinking? I also added a video for configuring visual studio code there. Apologies if it still isn't ideal.

**Comment by Timo614** [comment]
I've added some stubs for where I'll be placing photos. I'm taking the photos now as part of my demo video creation so will provide those in a zip file here once I'm set on both fronts. Let me know if something isn't ideal.

**Comment by Timo614** [comment]
Going to close this out, apologies here, the approach taken here was to create devices and then trigger automations based on that but the desired state is to have the matter app handle controlling other matter devices directly via the binding logic. Given this doesn't do that and I'm not sure of a way to do it on Google Home or Apple closing in favor of letting another developer with more experience grab the underlying issue.

**Review by MatthewJeffson — APPROVED** [review]
Thank you so much for the add up!

**Pull request merged**
